
output "cloudfront_endpoint" {
  description = "The site domain generated by Cloudfront."
  value = var.domain_name != "" ? module.cloudfront_with_domain[0].cloudfront_endpoint[0] : module.cloudfront_without_domain[0].cloudfront_endpoint[0]
}

output "custom_endpoint" {
  description = "The Route53 managed custom domain (if provided)."
  value = var.domain_name == "" ? "n/a" : var.domain_name
}